# Generated by Django 2.0.6 on 2018-06-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='number_posts',
        ),
    ]
